#!/bin/bash
mongo <<EOS
use Makespace
db.MakespaceEquipmentTypes.drop()
db.MakespaceEquipment.drop()
db.MakespaceNames.drop()
db.MakespacePeople.drop()
db.MakespaceEvents.drop()
db.MakespaceMachineLogs.drop()
db.MakespaceEventTemplates.drop()
db.MakepaceTimelines.drop()
EOS
mkdir -p user-pages member-pages equipment-type-pages equipment-pages event-pages
rm -f user-pages/* member-pages/* equipment-type-pages/* equipment-pages/* event-pages/* hack-pages/* allfobs.json
