event_type:             trainer_training
title:                  $equipment trainer training
duration:               150
attendance_limit:       2
host_prerequisites:
  - $equipment trainer
attendee_prerequisites:
  - $equipment user
