# Generated by Django 2.0.4 on 2018-04-14 14:44

from django.db import migrations, models
import django.db.models.deletion
import makespace_training_system.training_system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            bases=(makespace_training_system.training_system.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            bases=(makespace_training_system.training_system.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('G', 'Green'), ('A', 'Amber'), ('R', 'Red')], default='G', max_length=4)),
            ],
            bases=(makespace_training_system.training_system.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fob_number', models.CharField(blank=True, default='', max_length=32)),
                ('box_issued', models.DateField()),
                ('dietary_requirement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training_system.DietaryOption')),
            ],
            bases=(makespace_training_system.training_system.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(default='', max_length=128)),
                ('surname', models.CharField(default='', max_length=128)),
                ('known_as', models.CharField(blank=True, default='', max_length=128)),
                ('email', models.CharField(default='', max_length=256)),
                ('postal_address', models.CharField(default='', max_length=256)),
                ('photo_url', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('hide_photo', models.BooleanField(default=True)),
                ('announce_changes', models.BooleanField(default=False)),
                ('interests', models.TextField(blank=True, default='', max_length=2048)),
                ('membership_number', models.CharField(blank=True, default='', max_length=64)),
            ],
            bases=(makespace_training_system.training_system.models.BaseModel, models.Model),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training_system.EquipmentType'),
        ),
    ]
