# Generated by Django 2.0.4 on 2018-04-14 15:43

from django.db import migrations, models
import django.db.models.deletion
import makespace_training_system.training_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('training_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
            ],
            bases=(makespace_training_system.training_system.models.BaseModel, models.Model),
        ),
        migrations.AlterField(
            model_name='member',
            name='fob_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training_system.Fob'),
        ),
    ]
