# YAML file describing the data (almost like a schema)

# RHS words that look like type descriptions usually are type
# descriptions, but it's not really a DB schema; these are directions
# to the programs on what to do with these fields.

# The config data is kept as YAML rather than inside the mongodb
# database, so it can be version-controlled under git etc.

# Where there's a choice of whether to store data attached to a person
# or to something else, e.g. whether they are trained, or an owner, on
# a piece of equipment, we'll generally attach the data to a person,
# because, for example, training a person on a device changes the
# state of the person, not of the device.

person:
  status:
    ALL:
      fields:
        email:           email
        surname:         string
        given_name:      string
        known_as:        string
    registered:                 # anyone who has self-registered on the site e.g. with a view to doing See the Space
      fields:
        date_registered: date
      actions:
        - attend_meeting
        - signup_see_the_space
    interested:                 # people who have signed up for See the Space
      times_available: timeslots
    visited:                    # people who have done See the Space and are eligible to apply for induction
      fields:
        date_registered: date
        date_visited:    date
        times_available: timeslots
      actions:
        - signup_induction
    applicant:                  # people who have applied for induction
    member:                     # inducted members
      fields:
        date_registered: date
        date_visited:    date
        date_joined:     date
        times_available: timeslots
        inducted_by:     person
        date_suspended:  date   # there is no concept of leaving the organization, only suspending membership without rejoining since
        date_resumed:    date
        address:         postal
        # for each user, there are lists of their relationships with equipments
        trained_on:      [ (equipment_class, date) ]
        trainer_for:     [ (equipment_class, date) ]
        owner_for:       [ (equipment_class, date) ]
        merits:          number # keep track of people doing things for the space such as running training
        demerits:        number # keep track of number of times someone has signed up for something but not attended
        administrator:   date   # date since, instead of boolean
      times_available:   timeslots # see below for description of timeslots

# These make up bitmaps, which should fit into a Python integer, so
# assuming 7 days, you can have up to four time slots per day even on
# a 32-bit system.  A timeslots bitmap is part of a user's profile,
# and each event instance (e.g. a training session) has a time, so the
# system can work out who to offer slots to when a training session
# becomes available.

timeslots:
  days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    - Sunday
  periods:
    morning: 07:00 -- 12:30
    afternoon: 13:00 -- 18:00
    evening: 18:30 -- 22:00

# There'll be a template system for instantiating events for people to
# sign up to.  'requirement' describes the condition for being
# eligible to sign up for something, and 'transition' for what happens
# if the host confirms their successful attendance.

events:
  ALL:
    fields:
      date:        date
      start_time:  time
      duration:    duration
      hosts:       [member]
      registered:  [person]
      attended:    [person]
      declined:    [person]
      no_show:     [person]
      name:        string
      typename:    string
      description: string
  see_the_space:
    requirement: interested
    transition:  visited
    name:        See the Space
    typename:    See the Space
    description: A tour of the Space, required before applying to join (to make sure you know what you'll be signing up for).
    equipment:   makespace
  induction:
    requirement: visited
    transition:  member
    name:        New members' induction
    typename:    New members' induction
    description: The general induction and safety briefing for the space as a whole, that all new members must attend.
    equipment:   makespace
  training:
    requirement: member
    transition:  trained_on
    description: "Training on %(equipment_class)s"
    host:        trainer_for
    name:        "%(equipment_class)s training"
    typename:    Equipment training
    equipment:   "%(equipment_class)s"
    fields:
      equipment: equipment_class
  meeting:
    name:         "%(meeting_name)"
    description:  A meeting where people are sitting in rows of chairs, lecture-style.
    typename:     Meeting
    equipment:    classroom
    location:     classroom
    fields:
      location:   location
      max_people: 60
  hackathon:
    name:         "%(meeting_name)"
    description:  A meeting where people are sitting at tables.
    typename:     Hackathon
    equipment:    classroom
    location:     classroom
    fields:
      location:   location
      max_people: 30

# This section defines the names that can be used as locations in the
# "events" and "equipment_classes" sections
      
locations:
  main_space:
    name: Main space
  classroom:
    name: Classroom
    capacity:
      tables: 30
      seated: 60
  trove:
    name: Trove
  office:
    name: Office
  workshop:
    name: Secure workshop
  craft_room:
    name: Craft room
  corridor:
    name: Corridor
  kitchen:
    name: Cakespace

# The data which is the same for each piece of the same type of
# equipment, so we don't have to repeat it.  Members get trained on an
# equipment class, not an individual instance of the equipment.
    
equipment_classes:
  makespace:
    description: The hackerspace itself.  Its equipment training is the induction.
  makespace_admin_db:
    description: The admin database.  Being a user of it means you can read other people's data, and being an owner means you can write other people's data.
  laser_cutter:
    training_class: red
    manufacturer:   laserscript
  ultimaker:
    training_class: red
  formlabs:
    training_class: red
  vacuum_former:
    training_class: amber
    manufacturer:   Formech
  warco_metal_mill:
    manufacturer:   Warco
    training_class: red
  metal_lathe:
    training_class: red
  wood_lathe:
    training_class: red
  projector:
    training_class: green

training_classes:
  red:
    training_required: Yes
    training_available: Yes
  amber:
    training_required: No
    training_available: Yes
  green:
    training_required: No
    training_available: No

training:
  default_max_requests: 3
  no_shows_limit:       2
    
page:
  stylesheet:   config/makers.css
  style_inline: True
  # preamble:     <p>Top navigation bar etc will go here.</p>
  # postamble:    <p>Bottom navigation bar etc will go here.</p>
  motd_file:    config/motd.html

skill_areas:
  - Biohacking
  - Civic engineering
  - Clothes-making and modification
  - Electro-mechanical engineering
  - Electronic engineering
  - Environmental science
  - Fine arts
  - Flying things (drones, model aircraft, HAB, rocketry)
  - Historic technology
  - Home automation
  - Jewellery and ornament making
  - Lifehacking
  - Mechanical engineering
  - Metalwork
  - Optics
  - Pottery
  - Programming (general)
  - Programming (embedded)
  - Renewables
  - Sculpture and carving
  - Sewing, knitting, chrocheting, macrame, weaving, spinning etc
  - Steampunk
  - STEM outreach and public engagement
  - Wearable computing
  - Woodwork

database:
  URI: mongodb://localhost/
  database_name: Makespace
  collections:
    names:           MakespaceNames
    people:          MakespacePeople
    equipment_types: MakespaceEquipmentTypes
    machines:        MakespaceMachines
    machine_logs:    MakespaceMachineLogs
    events:          MakespaceEvents
    event_templates: MakespaceEventTemplates
    timelines:       MakepaceTimelines

# The names in this section indicate which equipment class names
# are magical

organization:
  # Being trained on the equipment class named here means being
  # inducted; being a trainer on it means being an inductor.
  name:          makespace
  title:         Makespace
  # Being a trained user on the equipment class named here gives you
  # read access to the database; being an owner on it gives you write access
  database:      makespace_admin_db
  # Being a trained user on the equipment class named here gives you
  # write access to the announcements system
  announcements: noticeboard

server:
  mailhost:       makespace.org
  base_url:       https://makers.makespace.org/
  update_profile: update_profile/
  rsvp_form:      rsvp_form/
  rsvp:           rsvp/
  machines:       equipment/
  types:          equipment-type/
  events:         event/
  admin:          admin/
  userapi:        api/users/

messages:
  templates_directory: /usr/local/share/makers/message_templates
