* Makespace database help
** Introduction

   This is the membership, equipment and training database for
   Makespace, a hackerspace in Cambridge, UK.

   It holds the following information:

   - the list of members
   - the list of equipment types
   - [the list of equipment instances --- not yet]
   - the list of events held at Makespace

   Through this system, you can:

   - maintain your user profile
   - check your training status for equipment
   - request training on equipment
   - schedule events
   - [check equipment status -- not yet]

   Makespace members are likely to be the type of people who like to
   form a good mental model of how something works, so we'll go
   straight in with the real key to understanding the system: it is
   centred around ``events'', of which the most important is
   training.  The system manages people's permissions to do things
   (such as use particular equipment), and those permissions are
   represented by having successfully attended events which grant
   those permissions (i.e. training).

   There are three "roles" in which you can be trained for each piece
   of equipment:

   - user
   - trainer
   - owner

   Users can use the equipment, trainers can create user training and
   trainer training events and can mark their successful completion,
   and owners can create maintenance and owner training events.

   There are some special classes of "equipment":

   - being an inducted member is represented by having been trained on
     "makespace" (and being an inductor is represented by having been
     trained as a Makespace trainer).

   - being a database admin is represented by having been trained as
     an owner of the "database" equipment (and being an auditor, which
     is a read-only admin, by being trained as a user of it).

   When a trainer schedules a training event, the system searches for
   users who have requested that type of training, sorts them into
   order of how long they've been waiting, and sends them emails
   containing offers of training, with links to click on to indicate
   acceptance or passing.

   There is a limit on the number of training requests you can have
   open at once, to encourage people to be specific about requesting
   training only on equipment they're serious about using.  Your
   personal limit can be raised by an admin if you can convince them
   that you have good reason; and we will experiment with the
   system-wide default number for this as we settle into using the
   system.

   If you don't turn up for training that you've signed up for more
   than a set number of times, you won't be able to request or accept
   more training until you've contacted an admin about it.  This may
   sound a bit draconian, but we have had real problems with people
   wasting training slots, which, as trainers are volunteering their
   time, are one of our scarcer resources.

** Things database admins can do

   There are some things admins can set on your profile that (to avoid
   the risk of misuse) you can't do yourself:

   - clear the flag that says you're a persistent non-attender of
     training
   - increase the number of training requests you can have open
   - ban you from equipment or from the space itself, and cancel the
     ban (bans are represented as untraining events)
   - correct your training status by creating training/untraining
     events
   - increase the number of training requests you can have open at
     once

** How your data is used

   We use your data primarily to keep track of who can use each type
   of equipment and schedule each type of event, and secondarily for
   other administrative tasks.

   As our number of members grows, we are outgrowing our old model of
   being a small group who know each other, and also the
   administrative load is growing, therefore we are increasing the
   automation of how we run the space.  Also, as the GDPR comes into
   effect, we don't want lists of people on a public wiki to be the
   only way we can indicate who can use equipment.  And,
   unfortunately, there are some people who, if they damage equipment,
   won't own up to it, and as we don't all know each other by name
   now, they can't necessarily be traced.  So, we are moving towards
   having a controller attached to each piece of equipment, with a
   keyfob reader, to enable the equipment only for those who have been
   trained on it, and will also keep a record of who used the
   equipment and when.

   To minimize the risk of personal identifying information leaking
   out, the information going to the equipment controllers will not
   include your name, but only your keyfob number (except for
   equipment that can be left running unattended, such as the 3-D
   printers, as they display the name associated with the current
   job).

** Leaving (and possibly re-joining)

   Your database entry is held in two separate databases, an
   identifying one containing your name, email address, etc, and an
   operational one containing no personal identifying information.
   There are two ways that you can leave the system:

   - having your entry in the identifying database deleted (leaving
     just an anonymous UUID in the operational database's log of
     events); this is what the GDPR requires us to offer.  We will
     tell you a UUID identifying your anonymized data, which may be
     helpful if you do decide to re-join despite having expected not
     to at the time you left.

   - having a de-training event applied (by an admin) to your
     Makespace training, which represents suspension of your
     membership until further notice.  This makes it easier to
     re-join, and (until an expiry time) allows your training status
     to be regained without going through re-training if you re-join.

   When you leave, you will be marked as de-trained on Makespace, and
   a future one-person de-training event will be scheduled for each
   piece of equipment you're trained on, with a delay specified by the
   configuration for that equipment.  If you re-join before then,
   those de-training events will be cancelled, and you will be able to
   resume using that equipment without re-training.

   If Makespace requires you to leave (bans you) for misconduct, we
   will keep your identifying information as required for operational
   reasons (to stop you re-joining).
