#!/bin/bash
# Copy To Server
rsync -av --exclude .git $HOME/open-projects/makers/ $REMOTE_USER@$SERVER:open-projects/makers
ssh $REMOTE_USER@$SERVER open-projects/makers/scripts/setperm.sh
ssh $REMOTE_USER@$SERVER sudo -u nginx /home/nginx/bin/install
ssh $REMOTE_USER@$SERVER sudo systemctl restart gunicorn
